### ISSUE TITLE
USER STORY: Provide additional comments for poll

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/user-stories#4]
As a **user** I can **add a comment before I submit my poll response** so that **I can provide additional thoughts beyond the response options**

## Acceptance Criteria
  
* Acceptance Criteria 1:
Comment box above the submit button but below the dropdown poll options.
* Acceptance Criteria 2:
Placeholder text in the box to say 'Add any additional comments here'.
* Acceptance Criteria 3:
Comments are optional, not required.

## Tasks

- [ ] Design comment box size, positioning, font style and size
- [ ] Create the HTML and CSS for the comment box
- [ ] Test the completed functionality
