### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/user-stories#5]
As an **administrator** I can **publish a poll** so that **I can collect users' feedback**

## Acceptance Criteria
  
* Acceptance Criteria 1:
The administrator can add a poll title
* Acceptance Criteria 2:
The administrator can add relevant drop down options for the user to select from

## Tasks

- [ ] Design the 'create a poll' icon and add it to the administrator's page
- [ ] Design the 'add a poll' form including a space to add the title and the dropdown options
- [ ] Create the HTML and CSS for the 'create a poll' icon and link to the 'add a poll' form
- [ ] Create the HTML and CSS for the title entry
- [ ] Create the HTML and CSS for the administrator to enter the dropdown options
- [ ] Create the code to translate the submitted 'add a poll' form into a feature that appears on the live page with the poll options as dropdown options
- [ ] Test the completed functionality
