### ISSUE TITLE
USER STORY: Expiry date for the poll

### ISSUE THREAD

**Issue by lhartley870** [lhartley870/user-stories#6]
As an **administrator** I can **pick the expiry date while publishing the poll** so that **I can automatically hide the poll **

## Acceptance Criteria
  
* Acceptance Criteria 1:
Checkbox to check for including an expiry date.
* Acceptance Criteria 2:
Dropdown boxes to enter the date, month and year for the expiry date.
* Acceptance Criteria 3:
Verification that the day exists in the month and year selected.
* Acceptance Criteria 4:
Verification that the date chosen is later than the date the poll was created.

## Tasks

- [ ] Design the positioning, font size and type for the poll expiry element of the 'add poll' form
- [ ] Create the HTML and CSS for the checkbox
- [ ] Create the HTML and CSS for the date dropdown box
- [ ] Create the HTML and CSS for the month dropdown box
- [ ] Create the HTML and CSS for the year dropdown box
- [ ] Create the code to verify that the day exists in the month and year selected
- [ ] Create the code to verify that the date chosen is later than the date the poll was created.
- [ ] Test the completed functionality
